<html>
  <head>
	<title>FeuilleToDoc</title>
	<link rel="stylesheet" href="http://localhost/onadabase/FeuilleToDoc/css/styles.css" type="text/css">
	<script type="text/javascript" src="http://www.google.com/jsapi"></script>
	<script type="text/javascript" src="http://localhost/onadabase/FeuilleToDoc/js/GoogleDocs.js"></script>
	<script type="text/javascript" src="http://localhost/onadabase/FeuilleToDoc/js/ajax.js"></script>
	<script type="text/javascript">
	 <?php echo "var nbrspeardsheet=".sizeof(json_decode($this->data)); echo "; Name=eval((".$this->data."));"; ?> 
     var result= new Array();var Nbr=2;var urlAjax="";var j=0;urlImg="";var f=0;var liste="";
     var signature= new Array();var in_array=false;var l=0;var id_feuil; var ul="";var m=0;urlRapport="rapports/";
     var urlSpreadsheet='http://spreadsheets.google.com/pub?key=';
     load();
    
   </script>
  </head>
	<body>
	 <h1>onadabase</h1> 
	 	<div id="main">
	 	<h4>Veuillez choisir le spreadsheet que vous voulais traité :</h4>
	 	<div id="MenuSpeardSheet"></div>
	 	<script type="text/javascript">getSpreadSheet(Name);</script>
	 	  <table id="table" border="1" align="center" style="visibility:hidden">
			 <tr>
			   
			   <td><button onclick="ViewRapport(Name[id_feuil]);">Afficher rapport</button></td>
			 </tr>
		     <tr>
		     	<td colspan="2">
		     		<ul id="ListeFeuilles">
		     		</ul>
		     	</td>
		     	
		     </tr> 	
		  </table>
	  </div>
	  <div id="right">
		<iframe id="ViewSpeardsheet" width='900' height='500' frameborder='0' src=''></iframe>
	  </div>
	  
	</body>

</html>
