<?php
session_start();
function ChercheAbo ()
	{
		
		$login=$_POST['login_uti'];
		$mdp=$_POST['mdp_uti'];
		
		if(($login=="")&&($mdp=="")){
			include("login.php");
			exit;
			
		}
}


ChercheAbo ();
?>
<html>
  <head>
	<title>FeuilleToDoc</title>
	<link rel="stylesheet" href="<?php echo WEBAPP_DIR; ?>/css/styles.css" type="text/css">
	<script type="text/javascript" src="http://www.google.com/jsapi"></script>
	<script type="text/javascript" src="<?php echo WEBAPP_DIR; ?>/js/GoogleDocs.js"></script>
	<script type="text/javascript" src="<?php echo WEBAPP_DIR; ?>/js/ajax.js"></script>
	<script type="text/javascript">
	 <?php echo "var nbrspeardsheet=".sizeof(json_decode($this->data)); echo "; var Name=eval((".$this->data."));"; ?> 
     var result= new Array();var urlAjax="";var j=0;
     var urlImg="<?php echo IMG_URL; ?>"; //adresse des images
     var f=0;var liste="";
     var l=0;var WorkSheetNbre; var ul="";var m=0;urlRapport="<?php echo RAPPORT_URL; ?>";var WorkSheetTitle;
     var urlSpreadsheet='http://spreadsheets.google.com/pub?key=';
     var trace = false;
	 var xmlParam = GetXmlUrlToDoc("<?php echo PARAM_URL."CritSup.xml"; ?>");
	 var xmlSols = GetXmlUrlToDoc("<?php echo PARAM_URL."solutions.xml"; ?>");
	 var idFeuille = 0;//n° de la feuille en cours de traitement
 	 var arrProb;//tableau des problèmes
     load();
    
   </script>
  </head>
	<body onload="getSpreadSheet(Name);">
	 <h1>onadabase</h1> 
	 	<div id="main">
	 	<h4 style="color:#000000">Veuillez choisir le spreadsheet que vous voulais traité :</h4>
	 	<div id="MenuSpeardSheet"></div>
	 	  <table id="table" border="1" align="center" style="visibility:hidden">
			 <tr>
			   
			   <td>
			   	<button onclick="CreaAllReport()">Calculer tout les rapports</button>
			   	<button onclick="ViewAllRapport()">Afficher le rapport total</button>
			   	<button onclick="ViewRapport()">Afficher rapport</button>
			   </td>
			 </tr>
		     <tr>
		     	<td colspan="2">
		     		<ul id="ListeFeuilles">
		     		</ul>
		     	</td>
		     	
		     </tr> 	
		  </table>
	  </div>
	  <div id="right">
		<iframe id="ViewSpeardsheet" width='900' height='500' frameborder='0' src=''></iframe>
	  </div>
	  
	</body>

</html>
